# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartmentNum', models.CharField(max_length=10, unique=True)),
                ('compartmentPosition', models.CharField(max_length=4)),
                ('numberOfItems', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=250, unique=True)),
                ('itemPic', models.CharField(max_length=1000)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Compartment')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfNum', models.CharField(max_length=10, unique=True)),
                ('shelfPosition', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='compartment',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Shelf'),
        ),
    ]
